db:
  address: ${DB_HOST}
  database: ${DB_DATABASE}
  username: ${DB_USER}
  password: ${DB_PASS}
oss:
  accessKey: ${OSS_ACCESS_KEY}
  bucket: ${OSS_BUCKET}
  secretKey: ${OSS_SECRET_KEY}
  endpoint: ${OSS_ENDPOINT}
  callback: ${OSS_CALLBACK}
email:
  address: ${ADDRESS}
  username: ${USERNAME}
  password: ${PASSWORD}
  host: ${HOST}
  pollCount: ${POLLCOUNT}


