db:
  address: 127.0.0.1:3306
  database: community
  username: root
  password: 123
kodo:
  accessKey: ${KODO_ACCESS_KEY}
  bucket: ${KODO_BUCKET}
  secretKey: ${KODO_SECRET_KEY}
  domain: ${DOMAIN}

