db:
  address: ${DB_HOST}
  database: ${DB_DATABASE}
  username: ${DB_USER}
  password: ${DB_PASS}
kodo:
  accessKey: ${KODO_ACCESS_KEY}
  bucket: ${KODO_BUCKET}
  secretKey: ${KODO_SECRET_KEY}
  domain: ${DOMAIN}

