name: build

on:
    push:
        tags:
            - 'v*'
jobs:
    get-latest-sources:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Get latest tag
          id: tag
          run: |
            git fetch --tags
            latest_tag=$(git describe --abbrev=0 --tags)
            git checkout $latest_tag

    build-back:
        needs: get-latest-sources
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
    
        - name: Set up Go
          uses: actions/setup-go@v4
          with:
            go-version: '1.19'
    
        - name: tidy
          run: go mod tidy
        - name: Test
          run: go test -v ./...
        - name: Build
          run: GOOS=linux go build -o ./dist/community ./cmd/community
    build-front:
        needs: get-latest-sources
        runs-on: ubuntu-latest
        steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Set up Node.js
          uses: actions/setup-node@v2
          with:
            node-version: 14

        - name: Install dependencies
          run: cd ./web && yarn install

        - name: Build Vue project
          run: yarn build && cp -r ./dist/* ../dist/web/